import { normalizePhone, validateCustomer } from '../lib/validate.js';
import { ordersToCsv } from '../lib/csv.js';
import { getPosts, getPost } from '../lib/blog.js';
import { formatPKR, slugify, discountPct } from '../lib/format.js';
const t = (name, ok) => { console.log(ok ? 'PASS' : 'FAIL', name); if (!ok) process.exitCode = 1; };
for (const p of ['0300-1234567','03001234567','+923001234567','923001234567','3001234567']) t('phone ' + p, normalizePhone(p)?.local === '03001234567');
for (const p of ['0200-1234567','0300123','abc','+92 300 123456789']) t('reject ' + p, normalizePhone(p) === null);
const good = { name:'Ahmed Ali', phone:'0300-1234567', address:'House 4, Street 2, Model Town', landmark:'near masjid', city:'Lahore', province:'Punjab' };
t('valid customer', validateCustomer(good).ok);
t('bad province', !validateCustomer({ ...good, province:'Mars' }).ok);
t('short address', !validateCustomer({ ...good, address:'abc' }).ok);
const csv = ordersToCsv([{ orderId:'MZ-1', createdAtMs:1760000000000, customer:{ name:'=cmd()', phone:'03001234567', address:'A, "B"', landmark:'L', city:'Lahore', province:'Punjab', notes:'' }, items:[{ name:'Boots', size:'43', qty:2 }], total:7000, status:'Pending' }]);
t('csv BOM', csv.charCodeAt(0) === 0xFEFF);
t('csv formula guard', csv.includes(`"'=cmd()"`));
t('csv phone text', csv.includes('="03001234567"'));
t('csv quote escape', csv.includes('"A, ""B"""'));
t('csv product line', csv.includes('Boots (Size 43) x2'));
const posts = getPosts();
t('6 posts', posts.length === 6);
t('post html + cta', getPost('cash-on-delivery-pakistan').html.includes('<!--cta-->'));
t('posts have headings', posts.every(p => p.heads.length >= 4));
t('format', formatPKR(3500) === 'Rs. 3,500' && slugify('Tactical Boots!') === 'tactical-boots' && discountPct(3000, 4000) === 25);
